export const GrpcMethods = {
  academicCourses: {
    getCourses: 'GetCourses',
    createCourse: 'CreateCourse',
    getCourseDetail: 'GetCourseDetail',
    updateCourse: 'UpdateCourse',
    deleteCourse: 'DeleteCourse',
  },
  academicClassrooms: {
    getClassrooms: 'GetClassrooms',
    createClassroom: 'CreateClassroom',
    getClassroomDetail: 'GetClassroomDetail',
    updateClassroom: 'UpdateClassroom',
    deleteClassroom: 'DeleteClassroom',
    regenerateInviteCode: 'RegenerateInviteCode',
    inviteClassMembers: 'InviteClassMembers',
  },
  academicLessons: {
    createLesson: 'CreateLesson',
    getLessonsByCourse: 'GetLessonsByCourse',
    getLessonDetail: 'GetLessonDetail',
    updateLesson: 'UpdateLesson',
    deleteLesson: 'DeleteLesson',
    publishLessonToClassroom: 'PublishLessonToClassroom',
    getClassroomLessons: 'GetClassroomLessons',
    updateClassroomLesson: 'UpdateClassroomLesson',
    removeLessonFromClassroom: 'RemoveLessonFromClassroom',
  },
  academicEnrollments: {
    joinClassroom: 'JoinClassroom',
    createEnrollment: 'CreateEnrollment',
    getClassroomStudents: 'GetClassroomStudents',
    updateEnrollmentRole: 'UpdateEnrollmentRole',
    removeEnrollment: 'RemoveEnrollment',
  },
  assessmentExams: {
    createExam: 'CreateExam',
    getExams: 'GetExams',
    getExamDetail: 'GetExamDetail',
    updateExam: 'UpdateExam',
    deleteExam: 'DeleteExam',
    publishExam: 'PublishExam',
    closeExam: 'CloseExam',
  },
  assessmentQuestions: {
    createQuestion: 'CreateQuestion',
    getExamQuestions: 'GetExamQuestions',
    getQuestionDetail: 'GetQuestionDetail',
    updateQuestion: 'UpdateQuestion',
    deleteQuestion: 'DeleteQuestion',
    reorderQuestions: 'ReorderQuestions',
  },
  assessmentSubmissions: {
    startExam: 'StartExam',
    getSubmissionDetail: 'GetSubmissionDetail',
    autosaveAnswers: 'AutosaveAnswers',
    submitSubmission: 'SubmitSubmission',
  },
  assessmentResults: {
    getResult: 'GetResult',
    manualGrade: 'ManualGrade',
  },
  assessmentAnalytics: {
    getExamAnalytics: 'GetExamAnalytics',
    getQuestionAnalytics: 'GetQuestionAnalytics',
    getStudentAnalytics: 'GetStudentAnalytics',
  },
  chatSessions: {
    createSession: 'CreateSession',
    getSessions: 'GetSessions',
    getSessionDetail: 'GetSessionDetail',
    updateSession: 'UpdateSession',
    deleteSession: 'DeleteSession',
  },
  chatMessages: {
    getMessages: 'GetMessages',
    createMessage: 'CreateMessage',
    getMessageDetail: 'GetMessageDetail',
    deleteMessage: 'DeleteMessage',
  },
  chatAnalytics: {
    getMyAnalytics: 'GetMyAnalytics',
    getClassroomAnalytics: 'GetClassroomAnalytics',
  },
  learningMaterials: {
    createMaterial: 'CreateMaterial',
    getMaterials: 'GetMaterials',
    getMaterialDetail: 'GetMaterialDetail',
    updateMaterial: 'UpdateMaterial',
    deleteMaterial: 'DeleteMaterial',
    getMaterialChunks: 'GetMaterialChunks',
    getChunkDetail: 'GetChunkDetail',
  },
  learningRoadmaps: {
    createRoadmap: 'CreateRoadmap',
    getRoadmaps: 'GetRoadmaps',
    getNextRoadmapItem: 'GetNextRoadmapItem',
    getRoadmapDetail: 'GetRoadmapDetail',
    updateRoadmap: 'UpdateRoadmap',
    deleteRoadmap: 'DeleteRoadmap',
    createRoadmapItem: 'CreateRoadmapItem',
    getRoadmapProgress: 'GetRoadmapProgress',
    updateRoadmapItem: 'UpdateRoadmapItem',
    deleteRoadmapItem: 'DeleteRoadmapItem',
    completeRoadmapItem: 'CompleteRoadmapItem',
    uncompleteRoadmapItem: 'UncompleteRoadmapItem',
  },
  learningMastery: {
    getMyMastery: 'GetMyMastery',
    getMasteryByClass: 'GetMasteryByClass',
    getMasteryByTopic: 'GetMasteryByTopic',
    getMasteryAnalytics: 'GetMasteryAnalytics',
    upsertMastery: 'UpsertMastery',
    bulkUpsertMastery: 'BulkUpsertMastery',
    getRiskStudents: 'GetRiskStudents',
  },
  storage: {
    deleteFile: 'DeleteFile',
  },
  users: {
    getUsers: 'GetUsers',
  },
  jobs: {
    getJobStatus: 'GetJobStatus',
    createJob: 'CreateJob',
    updateJobStatus: 'UpdateJobStatus',
    markJobRunning: 'MarkJobRunning',
    markJobSucceeded: 'MarkJobSucceeded',
    markJobFailed: 'MarkJobFailed',
  },
  notifications: {
    createNotification: 'CreateNotification',
    listMyNotifications: 'ListMyNotifications',
    getUnreadCount: 'GetUnreadCount',
    markNotificationRead: 'MarkNotificationRead',
    markAllNotificationsRead: 'MarkAllNotificationsRead',
  },
} as const;
