export const GrpcServices = {
  academicCourses: 'AcademicCoursesService',
  academicClassrooms: 'AcademicClassroomsService',
  academicLessons: 'AcademicLessonsService',
  academicEnrollments: 'AcademicEnrollmentsService',
  assessmentExams: 'AssessmentExamsService',
  assessmentQuestions: 'AssessmentQuestionsService',
  assessmentSubmissions: 'AssessmentSubmissionsService',
  assessmentResults: 'AssessmentResultsService',
  assessmentAnalytics: 'AssessmentAnalyticsService',
  chatSessions: 'ChatSessionsService',
  chatMessages: 'ChatMessagesService',
  chatAnalytics: 'ChatAnalyticsService',
  learningMaterials: 'LearningMaterialsService',
  learningRoadmaps: 'LearningRoadmapsService',
  learningMastery: 'LearningMasteryService',
  storage: 'StorageService',
  users: 'UsersService',
  jobs: 'JobsService',
  notifications: 'NotificationsService',
} as const;
