syntax = "proto3";

package chat;

import "common/json.proto";
import "google/protobuf/struct.proto";

service ChatMessagesService {
  rpc GetMessages(MessagesQuery) returns (common.PageResponse);
  rpc CreateMessage(MessageCreateRequest) returns (common.ObjectResponse);
  rpc GetMessageDetail(MessageIdRequest) returns (common.ObjectResponse);
  rpc DeleteMessage(MessageIdRequest) returns (common.DeleteResponse);
}

message MessageIdRequest {
  string message_id = 1;
}

message MessagesQuery {
  string session_id = 1;
  int32 page = 2;
  int32 limit = 3;
  string before = 4;
}

message MessageCreateRequest {
  string session_id = 1;
  google.protobuf.Struct body = 2;
}
