syntax = "proto3";

package users;

import "common/json.proto";

service UsersService {
  rpc GetUsers(UserQuery) returns (common.PageResponse);
  rpc GetMe(common.EmptyRequest) returns (common.ObjectResponse);
  rpc UpdateMyProfile(UpdateMyProfileRequest) returns (common.ObjectResponse);
  rpc SyncClerkUserCreated(SyncClerkUserRequest) returns (common.ObjectResponse);
  rpc SyncClerkUserUpdated(SyncClerkUserRequest) returns (common.ObjectResponse);
  rpc SyncClerkUserDeleted(SyncClerkUserDeletedRequest) returns (common.ObjectResponse);
  rpc AssignUserRoles(AssignUserRolesRequest) returns (common.ObjectResponse);
  rpc GetRoles(common.EmptyRequest) returns (common.ListResponse);
  rpc GetPermissions(common.EmptyRequest) returns (common.ListResponse);
}

message UserQuery {
  string search = 1;
  string role = 2;
  int32 page = 3;
  int32 limit = 4;
}

message UpdateMyProfileRequest {
  string firstName = 1;
  string lastName = 2;
  string imageUrl = 3;
}

message SyncClerkUserRequest {
  string id = 1;
  string email = 2;
  string firstName = 3;
  string lastName = 4;
  string imageUrl = 5;
  string status = 6;
}

message SyncClerkUserDeletedRequest {
  string id = 1;
}

message AssignUserRolesRequest {
  string userId = 1;
  repeated string roles = 2;
}
